source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'
use_frameworks!

target 'YLNote' do


  config = use_native_modules!
    
  use_react_native!(
                    :path => config[:reactNativePath],
                    # to enable hermes on iOS, change `false` to `true` and then install pods
                    :hermes_enabled => false,
                    )
                    
                    
                    # Enables Flipper.
                    #
                    # Note that if you have use_frameworks! enabled, Flipper will not work and
                    # you should disable the next line.
                    # use_flipper!()
                    
                    pod 'JSPatch'
                    pod 'Masonry'
                    pod 'MJExtension'
                    pod 'NullSafe'
                    pod 'YYModel'
                    pod 'YBImageBrowser'
                    pod 'SnapKit'
                    pod 'AFNetworking','~> 3.0' #,'~> 2.4'
                    pod 'FMDB'
                    
                                        
                    target 'YLNoteTests' do
                      inherit! :search_paths
                      # Pods for testing
                    end
                    
                    target 'YLNoteUITests' do
                      # Pods for testing
                    end
                    
end
